/**
 *
 */
package de.dnb.gnd.utils.mx;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.List;

/**
 * @author baumann
 *
 */
public class Liste {

  public static String liste =
    "0001\tBerlin SBB\tDE-1\t\tDE-1\tStaatsbibliothek zu Berlin - Preußischer Kulturbesitz, Haus Unter den Linden\n"
      + "0003\tHalle ULB\tDE-3\tFE\tDE-601\tUniversitäts- und Landesbibliothek Sachsen-Anhalt / Zentrale\n"
      + "0003\tHalle ULB\tDE-3\tSPRACH\tDE-601\tUniversitäts- und Landesbibliothek Sachsen-Anhalt / Zentrale\n"
      + "0003\tHalle ULB\tDE-3\t\tDE-1\tUniversitäts- und Landesbibliothek Sachsen-Anhalt / Zentrale\n"
      + "0003\tHalle ULB\tDE-3\tFE-VD-17\tDE-12\tUniversitäts- und Landesbibliothek Sachsen-Anhalt / Zentrale\n"
      + "0004\tMarburg UB\tDE-4\t\tDE-603\tUniversität Marburg, Universitätsbibliothek\n"
      + "0004\tMarburg UB\tDE-4\tFE\tDE-4\tUniversität Marburg, Universitätsbibliothek\n"
      + "0007\tGoettingen SUB\tDE-7\tFE-VD-17\tDE-12\tNiedersächsische Staats- und Universitätsbibliothek Göttingen\n"
      + "0007\tGoettingen SUB\tDE-7\t\tDE-601\tNiedersächsische Staats- und Universitätsbibliothek Göttingen\n"
      + "0007\tGOETTINGEN MATH. INST.\tDE-7-003\t\tDE-601\tUniversität Göttingen, Mathematisches Institut, Bibliothek\n"
      + "0007\tGoettingen UB Bibl. d. Jur. Sem.\tDE-7-037\t\tDE-601\tUniversität Göttingen, Zentralbibliotheken der Juristischen Fakultät\n"
      + "0007\tGoettingen Sem. Dt. Phil.\tDE-7-052\t\tDE-601\tUniversität Göttingen, Seminar für Deutsche Philologie, Bibliothek\n"
      + "0008\tKiel UB\tDE-8\tSPRACH\tDE-8\tUniversitätsbibliothek Kiel, Zentralbibliothek\n"
      + "0008\tKiel UB\tDE-8\tFE-VD-17\tDE-12\tUniversitätsbibliothek Kiel, Zentralbibliothek\n"
      + "0008\tKiel UB\tDE-8\t\tDE-601\tUniversitätsbibliothek Kiel, Zentralbibliothek\n"
      + "0009\tGreifswald UB\tDE-9\t\tDE-601\tUniversitätsbibliothek Greifswald\n"
      + "0012\tMuenchen BSB\tDE-12\t\tDE-12\tBayerische Staatsbibliothek\n"
      + "0014\tDresden SLUB\tDE-14\t\tDE-576\tSächsische Landesbibliothek - Staats- und Universitätsbibliothek Dresden\n"
      + "0015\tLeipzig UB\tDE-15\t\tDE-576\tUniversitätsbibliothek Leipzig\n"
      + "0016\tHeidelberg UB\tDE-16\t\tDE-576\tUniversitätsbibliothek Heidelberg\n"
      + "0016\tHeidelberg HSbibliographie\tDE-16-250\t\tDE-576\tHeiBIB - Die Heidelberger Universitätsbibliographie\n"
      + "0016\tHeidelberg UB, SAI, SE\tDE-16-77\t\tDE-576\tCentre for Asian and Transcultural Studies (CATS), Abteilung Südasien\n"
      + "0017\tDarmstadt ULB\tDE-17\t\tDE-603\tTU Darmstadt, Universitäts- und Landesbibliothek - Stadtmitte\n"
      + "0017\tDarmstadt ULB\tDE-17\tFE\tDE-17\tTU Darmstadt, Universitäts- und Landesbibliothek - Stadtmitte\n"
      + "0018\tHamburg SUB\tDE-18\tSE\tDE-601\tStaats- und Universitätsbibliothek Hamburg Carl von Ossietzky\n"
      + "0018\tHamburg SUB\tDE-18\tFE\tDE-601\tStaats- und Universitätsbibliothek Hamburg Carl von Ossietzky\n"
      + "0018\tHamburg SUB\tDE-18\tSPRACH\tDE-18\tStaats- und Universitätsbibliothek Hamburg Carl von Ossietzky\n"
      + "0018\tHamburg SUB\tDE-18\tFE-VD-17\tDE-12\tStaats- und Universitätsbibliothek Hamburg Carl von Ossietzky\n"
      + "0018\tHamburg HAW\tDE-18-302\t\tDE-601\tHochschule für Angewandte Wissenschaften Hamburg, Hochschulinformations- und Bibliotheksservice (HIBS), Fachbibliothek Technik, Wirtschaft, Informatik\n"
      + "0018\tHamburg SUB Zentr. Normd.\tDE-18-312\t\tDE-18\tZentrale Stelle für Normdaten der Fachbibliotheken der Universität Hamburg\n"
      + "0018\tHamburg UKE\tDE-18-64\t\tDE-18\tUniversitätsklinikum Hamburg-Eppendorf, Ärztliche Zentralbibliothek\n"
      + "0019\tMuenchen UB\tDE-19\t\tDE-19\tUniversitätsbibliothek der LMU München\n"
      + "0020\tWuerzburg UB\tDE-20\t\tDE-20\tUniversitätsbibliothek Würzburg\n"
      + "0021\tTuebingen UB\tDE-21\t\tDE-576\tUniversitätsbibliothek der Eberhard Karls Universität\n"
      + "0023\tWolfenbuettel HAB\tDE-23\tFE\tDE-601\tHerzog August Bibliothek Wolfenbüttel\n"
      + "0023\tWolfenbuettel HAB\tDE-23\t\tDE-12\tHerzog August Bibliothek Wolfenbüttel\n"
      + "0024\tStuttgart Wuertt. LB\tDE-24\t\tDE-576\tWürttembergische Landesbibliothek\n"
      + "0025\tFreiburg UB\tDE-25\t\tDE-576\tUniversitätsbibliothek Freiburg\n"
      + "0026\tGiessen UB\tDE-26\t\tDE-603\tUniversitätsbibliothek Gießen\n"
      + "0026\tGiessen UB\tDE-26\tFE\tDE-26\tUniversitätsbibliothek Gießen\n"
      + "0027\tJena THULB\tDE-27\t\tDE-601\tThüringer Universitäts- und Landesbibliothek\n"
      + "0028\tRostock UB\tDE-28\tFE\tDE-28\tUniversitätsbibliothek Rostock\n"
      + "0028\tRostock UB\tDE-28\t\tDE-601\tUniversitätsbibliothek Rostock\n"
      + "0029\tErlangen UB\tDE-29\t\tDE-29\tUniversitätsbibliothek Erlangen-Nürnberg, Hauptbibliothek\n"
      + "0030\tFrankfurt/M StuUB\tDE-30\t\tDE-603\tUniversitätsbibliothek J. C. Senckenberg, Zentralbibliothek (ZB)\n"
      + "0030\tFrankfurt/M StuUB\tDE-30\tFE\tDE-30\tUniversitätsbibliothek J. C. Senckenberg, Zentralbibliothek (ZB)\n"
      + "0031\tKarlsruhe BLB\tDE-31\t\tDE-576\tBadische Landesbibliothek\n"
      + "0032\tWeimar HAAB\tDE-32\t\tDE-601\tKlassik Stiftung Weimar / Herzogin Anna Amalia Bibliothek\n"
      + "0033\tSchwerin LBMV\tDE-33\t\tDE-601\tLandesbibliothek Mecklenburg-Vorpommern Günther Uecker im Landesamt für Kultur und Denkmalpflege\n"
      + "0034\tKassel GHB\tDE-34\t\tDE-603\tUniversitätsbibliothek Kassel, Landesbibliothek und Murhardsche Bibliothek der Stadt Kassel\n"
      + "0034\tKassel GHB\tDE-34\tFE\tDE-34\tUniversitätsbibliothek Kassel, Landesbibliothek und Murhardsche Bibliothek der Stadt Kassel\n"
      + "0035\tHannover NLB\tDE-35\tFE\tDE-601\tGottfried Wilhelm Leibniz Bibliothek - Niedersächsische Landesbibliothek\n"
      + "0035\tHannover NLB\tDE-35\tFE-VD-17\tDE-12\tGottfried Wilhelm Leibniz Bibliothek - Niedersächsische Landesbibliothek\n"
      + "0036\tMainz StBi\tDE-36\t\tDE-603\tWissenschaftliche Stadtbibliothek\n"
      + "0036\tMainz StBi\tDE-36\tFE\tDE-36\tWissenschaftliche Stadtbibliothek\n"
      + "0038\tKöln UuSTB\tDE-38\t\tDE-605\tUniversitäts- und Stadtbibliothek Köln, Hauptabteilung\n"
      + "0043\tWiesbaden LB\tDE-43\t\tDE-603\tHochschul- und Landesbibliothek RheinMain, Rheinstraße\n"
      + "0043\tWiesbaden LB\tDE-43\tFE\tDE-43\tHochschul- und Landesbibliothek RheinMain, Rheinstraße\n"
      + "0045\tOldenburg LB\tDE-45\t\tDE-601\tLandesbibliothek Oldenburg\n"
      + "0046\tBremen SuUB\tDE-46\t\tDE-601\tStaats- und Universitätsbibliothek Bremen\n"
      + "0048\tLuebeck StB\tDE-48\t\tDE-601\tBibliothek der Hansestadt Lübeck\n"
      + "0056\tBraunschweig StBi\tDE-56\tFE-VD-17\tDE-12\tStadtbibliothek Braunschweig\n"
      + "0056\tBraunschweig StBi\tDE-56\t\tDE-601\tStadtbibliothek Braunschweig\n"
      + "0059\tChemnitz STB\tDE-59\t\tDE-576\tStadt Chemnitz, Kulturbetrieb, Stadtbibliothek\n"
      + "0066\tFulda HLB\tDE-66\t\tDE-603\tHochschul- und Landesbibliothek Fulda, Standort Heinrich-von-Bibra-Platz\n"
      + "0066\tFulda HLB\tDE-66\tFE\tDE-66\tHochschul- und Landesbibliothek Fulda, Standort Heinrich-von-Bibra-Platz\n"
      + "0068\tKiel LB\tDE-68\t\tDE-601\tSchleswig-Holsteinische Landesbibliothek\n"
      + "0075\tNuernberg StB\tDE-75\t\tDE-12\tStadtbibliothek im Bildungscampus Nürnberg\n"
      + "0077\tMainz UB\tDE-77\t\tDE-603\tUniversität Mainz, Zentralbibliothek\n"
      + "0077\tMainz UB\tDE-77\tFE\tDE-77\tUniversität Mainz, Zentralbibliothek\n"
      + "0083\tBerlin, UB TU\tDE-83\tSE\tDE-188\tTU Berlin, Universitätsbibliothek\n"
      + "0083\tBerlin, UB TU\tDE-83\tFE\tDE-384\tTU Berlin, Universitätsbibliothek\n"
      + "0083\tBerlin, UB TU\tDE-83\t\tDE-83\tTU Berlin, Universitätsbibliothek\n"
      + "0084\tBraunschweig UB TU\tDE-84\t\tDE-601\tUniversitätsbibliothek Braunschweig\n"
      + "0089\tHannover TIB/UB\tDE-89\t\tDE-601\tTechnische Informationsbibliothek (TIB) / Leibniz-Informationszentrum Technik und Naturwissenschaften und Universitätsbibliothek\n"
      + "0090\tKarlsruhe UB (KIT)\tDE-90\t\tDE-576\tKarlsruher Institut für Technologie, KIT-Bibliothek\n"
      + "0091\tMuenchen TU\tDE-91\t\tDE-91\tTechnische Universität München, Universitätsbibliothek\n"
      + "0093\tStuttgart UB\tDE-93\t\tDE-576\tUniversitätsbibliothek Stuttgart\n"
      + "0095\tHannover TierHS\tDE-95\t\tDE-601\tStiftung Tierärztliche Hochschule Hannover, Bibliothek\n"
      + "0100\tStuttgart-Hoh. KIM\tDE-100\t\tDE-576\tKommunikations-, Informations- und Medienzentrum der Universität Hohenheim\n"
      + "0103\tSBB / ZKA\tDE-611\t\tDE-611\tStaatsbibliothek zu Berlin - Preußischer Kulturbesitz, Kalliope-Verbund\n"
      + "0104\tClausthal-Z. UB\tDE-104\t\tDE-600\tUniversitätsbibliothek Clausthal\n"
      + "0105\tFreiberg TU BA\tDE-105\t\tDE-576\tTechnische Universität Bergakademie Freiberg, Bibliothek 'Georgius Agricola'\n"
      + "0125\tZwickau RSB\tDE-125\t\tDE-576\tRatsschulbibliothek, Wissenschaftliche Bibliothek\n"
      + "0180\tMannheim UB\tDE-180\t\tDE-576\tUniversitätsbibliothek Mannheim\n"
      + "0188\tBerlin UB FU\tDE-188\t\tDE-602\tFreie Universität Berlin, Universitätsbibliothek\n"
      + "0204\tBerlin IAI\tDE-204\t\tDE-204\tIbero-Amerikanisches Institut Preußischer Kulturbesitz, Bibliothek\n"
      + "0206\tKiel ZBW\tDE-206\t\tDE-601\tZBW - Leibniz-Informationszentrum Wirtschaft, Standort Kiel\n"
      + "0208\tKarlsruhe BGH\tDE-208\t\tDE-576\tBibliothek des Bundesgerichtshofs\n"
      + "0212\tStuttgart Inst. Auslandsbez\tDE-212\t\tDE-576\tInstitut für Auslandsbeziehungen, Bibliothek\n"
      + "0253\tBraunschweig FAL\tDE-253\t\tDE-601\tThünen-Institut, Bundesforschungsinstitut für Ländliche Räume, Wald und Fischerei, Zentrum für Informationsmanagement\n"
      + "0255\tMuenchen ZIKG\tDE-255\t\tDE-612\tZentralinstitut für Kunstgeschichte, Bibliothek\n"
      + "0255\tRom Bibl. Hertziana\tDE-Y2\t\tDE-612\tBibliotheca Hertziana - Max-Planck-Institut für Kunstgeschichte\n"
      + "0255\tFlorenz KHI\tDE-Y3\t\tDE-612\tKunsthistorisches Institut in Florenz, Max-Planck-Institut, Bibliothek\n"
      + "0255\tParis DFK\tDE-Y7\t\tDE-612\tDeutsches Forum für Kunstgeschichte, Bibliothek\n"
      + "0281\tBerlin Bundestag Bibliothek\tDE-281\t\tDE-281\tDeutscher Bundestag, Bibliothek\n"
      + "0289\tUlm UB (KIZ)\tDE-289\t\tDE-576\tUniversität Ulm, Kommunikations- und Informationszentrum, Bibliotheksservices\n"
      + "0291\tSaarbruecken UuLB\tDE-291\t\tDE-576\tSaarländische Universitäts- und Landesbibliothek\n"
      + "0296\tSingen Hegau-B\tDE-296\t\tDE-576\tHegau-Bibliothek\n"
      + "0352\tKonstanz UB\tDE-352\t\tDE-576\tUniversität Konstanz, Kommunikations-, Informations-, Medienzentrum (KIM)\n"
      + "0354\tHannover Med. HS\tDE-354\t\tDE-601\tMedizinische Hochschule Hannover, Bibliothek\n"
      + "0355\tRegensburg UB\tDE-355\t\tDE-355\tUniversitätsbibliothek Regensburg\n"
      + "0384\tAugsburg UB\tDE-384\t\tDE-384\tUniversitätsbibliothek Augsburg\n"
      + "0460\tDarmstadt Staatsarchiv\tDE-460\t\tDE-603\tHessisches Staatsarchiv Darmstadt, Bibliothek\n"
      + "0468\tWuppertal UB\tDE-468\t\tDE-605\tUniversitätsbibliothek Wuppertal\n"
      + "0473\tBamberg UB\tDE-473\t\tDE-473\tUniversitätsbibliothek Bamberg\n"
      + "0500\tHBZ\tDE-605\t\tDE-605\thbz - Hochschulbibliothekszentrum des Landes Nordrhein-Westfalen\n"
      + "0517\tPotsdam UB\tDE-517\t\tDE-601\tUniversität Potsdam, Universitätsbibliothek\n"
      + "0521\tFrankfurt/O UB\tDE-521\t\tDE-521\tEuropa-Universität Viadrina, Universitätsbibliothek\n"
      + "0522\tBrandenburg FH\tDE-522\t\tDE-521\tTechnische Hochschule Brandenburg, Hochschulbibliothek\n"
      + "0523\tBerlin HTW\tDE-523\t\tDE-521\tHochschule für Technik und Wirtschaft Berlin, Hochschulbibliothek\n"
      + "0526\tWildau TH\tDE-526\t\tDE-521\tTechnische Hochschule Wildau [FH], Hochschulbibliothek\n"
      + "0540\tDresden HfBK FE\tDE-540\t\tDE-576\tHochschule für Bildende Künste Dresden, Bibliothek\n"
      + "0547\tErfurt UB\tDE-547\t\tDE-601\tUniversitätsbibliothek Erfurt / Forschungsbibliothek Gotha, Universitätsbibliothek Erfurt\n"
      + "0547\tErfurt/Gotha UFB\tDE-547\tFE-VD-17\tDE-12\tUniversitätsbibliothek Erfurt / Forschungsbibliothek Gotha, Universitätsbibliothek Erfurt\n"
      + "0563\tRostock HS Musik\tDE-563\t\tDE-601\tHochschule für Musik und Theater Rostock, Bibliothek\n"
      + "0600\tHeBIS\tDE-603\t\tDE-603\tHessisches BibliotheksInformationsSystem HeBIS\n"
      + "0614\tMuenster Int.Port.Westf.Gesch\tDE-614\t\tDE-614\tInternet-Portal \"Westfälische Geschichte\"\n"
      + "0631\tStuttgart LABI BAW\tDE-631\t\tDE-576\tLandesbibliographie Baden-Württemberg, Zentralredaktion\n"
      + "0700\tOsnabrueck UB\tDE-700\t\tDE-700\tUniversitätsbibliothek Osnabrück\n"
      + "0703\tBayreuth UB\tDE-703\t\tDE-703\tUniversitätsbibliothek Bayreuth\n"
      + "0705\tHamburg UniBW (HSU)\tDE-705\t\tDE-601\tHelmut-Schmidt-Universität, Universität der Bundeswehr Hamburg, Universitätsbibliothek\n"
      + "0706\tMuenchen UniBW\tDE-706\t\tDE-706\tUniversität der Bundeswehr München, Universitätsbibliothek\n"
      + "0715\tOldenburg BIS\tDE-715\t\tDE-601\tBibliotheks-und Informationssystem der Carl von Ossietzky Universität Oldenburg (BIS)\n"
      + "0739\tPassau UB\tDE-739\t\tDE-739\tUniversitätsbibliothek Passau\n"
      + "0747\tWeingarten HSB\tDE-747\t\tDE-576\tHochschulbibliothek Weingarten\n"
      + "0755\tEmden/Leer FH\tDE-755\t\tDE-601\tHochschule Emden/Leer, Hochschulbibliothek\n"
      + "0824\tEichstaett UB\tDE-824\t\tDE-824\tUniversitätsbibliothek Eichstätt-Ingolstadt\n"
      + "0830\tHamburg UB TU\tDE-830\t\tDE-601\tTechnische Universität Hamburg, Universitätsbibliothek\n"
      + "0832\tKoeln FHB, SE\tDE-832\t\tDE-832\tTechnische Hochschule Köln, Hochschulbibliothek\n"
      + "0834\tBraunschweig HBK\tDE-834\t\tDE-601\tHochschule für Bildende Künste Braunschweig, Bibliothek\n"
      + "0839\tWHV Jade Hochschule\tDE-839\t\tDE-601\tJade Hochschule Wilhelmshaven/Oldenburg/Elsfleth, Campus Wilhelmshaven, Bibliothek\n"
      + "0897\tOldenburg Jade-Hochschule\tDE-897\t\tDE-601\tJade Hochschule Wilhelmshaven/Oldenburg/Elsfleth, Campus Oldenburg, Bibliothek\n"
      + "0897\tElsfleth Jade HS\tDE-897-1\t\tDE-601\tJade Hochschule Wilhelmshaven/Oldenburg/Elsfleth, Campus Elsfleth, Bibliothek\n"
      + "0916\tWolfenbuettel FH\tDE-916\t\tDE-601\tOstfalia Hochschule für angewandte Wissenschaften, Bibliothek\n"
      + "0929\tKoblenz LB\tDE-929\t\tDE-605\tLandesbibliothekszentrum Rheinland-Pfalz / Rheinische Landesbibliothek\n"
      + "0955\tRottenburg HS Forstw\tDE-955\t\tDE-576\tHochschule für Forstwirtschaft Rottenburg, Bibliothek\n"
      + "0960\tHannover FHB\tDE-960\t\tDE-601\tBibliothek der Hochschule Hannover\n"
      + "0969\tWiesbaden FHB\tDE-969\t\tDE-603\tWiesbaden FHB\n"
      + "0974\tGiessen-Friedberg FHB\tDE-974\t\tDE-603\tTechnische Hochschule Mittelhessen, Hochschulbibliothek Gießen\n"
      + "0984\tSchwäbisch Gmünd HS Gestalt.\tDE-984\t\tDE-576\tHochschule für Gestaltung Schwäbisch Gmünd, Bibliothek\n"
      + "0996\tHannover HMTM/FMG\tDE-996\tFE\tDE-1\tHochschule für Musik, Theater und Medien Hannover, Bibliothek\n"
      + "0996\tHannover HMTM/FMG\tDE-996\tGKD\tDE-601\tHochschule für Musik, Theater und Medien Hannover, Bibliothek\n"
      + "1015\tDarmstadt Ev. HS\tDE-1015\t\tDE-603\tEvangelische Hochschule Darmstadt, Bibliothek\n"
      + "1031\tBerlin SBB\tDE-1\tFE\tDE-601\tStaatsbibliothek zu Berlin - Preußischer Kulturbesitz, Haus Unter den Linden\n"
      + "1158\tGuestrow FH oeff. Verw.\tDE-1158\t\tDE-601\tFachhochschule für öffentliche Verwaltung, Polizei und Rechtspflege des Landes Mecklenburg-Vorpommern, Bibliothek\n"
      + "1402\tOENDV\tAT-NOeLB\t\tAT-NOELB\tNiederösterreichische Landesbibliothek\n"
      + "1500\tSWB\tDE-576\t\tDE-576\tBibliotheksservice-Zentrum Baden-Württemberg (BSZ)\n"
      + "1510\tBSZ Baden-Wuerttemberg - PND\tDE-576-2\t\tDE-576\tfrüher: Konstanz; Bibliotheksservice-Zentrum Baden-Württemberg, Autorenredaktion\n"
      + "1520\tReutlingen EKZ\tDE-Rt5\t\tDE-576\tekz.bibliotheksservice GmbH\n"
      + "1600\tBern NB\tCH-000001-5\t\tCH-000001-5\tSchweizerische Nationalbibliothek\n"
      + "1610\tIDS-SE\tCH-IDSGNDS\t\tCH-IDSGNDS\tIDS-SE\n"
      + "1702\tNeuendetttelsau VThK (THB)\tDE-613\t\tDE-613\tVirtueller Katalog Theologie und Kirche\n"
      + "1703\tBremen Stiftung FLF / DaSinD\tDE-Bre15\t\tDE-Bre15\tStiftung Frauen-Literatur-Forschung e.V.\n"
      + "1704\tBonn GESIS\tDE-587b\t\tDE-587b\tfrüher: GESIS  - Leibniz-Institut für Sozialwissenschaften,  Bibliothek Bonn\n"
      + "1705\tKoblenz Bundesarchiv\tDE-1958\t\tDE-604\tBundesarchiv\n"
      + "1706\tBraunschweig PTB\tDE-Bs68\t\tDE-601\tPhysikalisch-Technische Bundesanstalt, Bibliothek\n"
      + "1707\tBraunschweig GEI\tDE-Bs78\t\tDE-601\tGeorg-Eckert-Institut - Leibniz-Institut für internationale Schulbuchforschung, Bibliothek\n"
      + "1711\tBerlin DZA\tDE-B1562\t\tDE-601\tDeutsches Zentrum für Altersfragen e.V. (DZA), Bibliothek\n"
      + "1712\tGatersleben IPK\tDE-Gat1\t\tDE-Gat1\tLeibniz-Institut für Pflanzengenetik und Kulturpflanzenforschung (IPK), Wissenschaftliche Bibliothek / Dokumentation\n"
      + "1713\tKiel FH\tDE-Ki95\t\tDE-601\tFachhochschule Kiel, Zentralbibliothek\n"
      + "1714\tHamburg MKG\tDE-H22\t\tDE-601\tGerd Bucerius Bibliothek im Museum für Kunst und Gewerbe\n"
      + "1715\tBerlin Stiftung Aufarbeitung\tDE-B1548\t\tDE-B1548\tStiftung zur Aufarbeitung der SED-Diktatur, Bibliothek\n"
      + "1716\tFrankfurt DIF\tDE-Wi17FP\t\tDE-101\tDFF - Deutsches Filminstitut & Filmmuseum / filmportal.de\n"
      + "1717\tHildesheim Dombibliothek\tDE-Hil6\t\tDE-601\tDombibliothek Hildesheim\n"
      + "1718\tBerlin BfR\tDE-B12\t\tDE-B12\tBundesinstitut für Risikobewertung, Bibliothek\n"
      + "1719\tHannover LT Nie\tDE-Hv14\t\tDE-601\tNiedersächsischer Landtag, Bibliothek\n"
      + "1720\tKarlsruhe BFI\tDE-Ka51\t\tDE-Ka51\tMax Rubner-Institut, Bundesforschungsinstitut für Ernährung und Lebensmittel, Standort Karlsruhe, Bibliothek, Information und Dokumentation\n"
      + "1721\tJena FLI\tDE-J120\t\tDE-J120\tFriedrich-Loeffler-Institut, Bundesforschungsinstitut für Tiergesundheit, Bibliothek Jena\n"
      + "1722\tWeimar HS Musik\tDE-Wim8\t\tDE-601\tHochschule für Musik Franz Liszt, Hochschulbibliothek\n"
      + "1723\tBerlin Hertie School\tDE-B1570\t\tDE-601\tHertie School, Library and Information Services\n"
      + "1724\tHildesheim Nieders. LRH\tDE-Hil5\t\tDE-601\tNiedersächsischer Landesrechnungshof, Bibliothek und Informationsdienste\n"
      + "1725\tWismar FH\tDE-Wis1\t\tDE-601\tHochschule Wismar, University of Applied Sciences: Technology, Business and Design, Hochschulbibliothek\n"
      + "1727\tBerlin Dt. Inst.f.Menschenr.,FE\tDE-B1547\t\tDE-601\tDeutsches Institut für Menschenrechte, Bibliothek\n"
      + "1728\tMarburg Hess Landesamt\tDE-Mb107\t\tDE-Mb107\tHessisches Landesamt für geschichtliche Landeskunde, Landesgeschichtliches Informationssystem Hessen\n"
      + "1729\tEmden JALB\tDE-Em2\t\tDE-601\tJohannes a Lasco Bibliothek Große Kirche Emden\n"
      + "1730\tGoettingen GWDG\tDE-Goe168\t\tDE-601\tGesellschaft für wissenschaftliche Datenverarbeitung mbH Göttingen (GWDG), Bibliothek\n"
      + "1732\tHamburg Bucerius Law School\tDE-H360\t\tDE-601\tBucerius Law School, Hochschule für Rechtswissenschaft, \"Hengeler Mueller\"-Bibliothek\n"
      + "1733\tIlmenau UB\tDE-Ilm1\t\tDE-601\tUniversitätsbibliothek Ilmenau\n"
      + "1734\tJena FH\tDE-J59\t\tDE-601\tErnst-Abbe-Hochschule Jena, Wissenschaftliche Bibliothek\n"
      + "1735\tJena Thuering. OLG\tDE-J153\t\tDE-601\tJustizzentrum Jena, Bibliothek\n"
      + "1736\tMagdeburg UB\tDE-Ma9\t\tDE-601\tOtto-von-Guericke-Universität, Universitätsbibliothek\n"
      + "1737\tOldenburg Ev.Luth. Oberk.\tDE-Old3\t\tDE-601\tEvangelisch-Lutherischer Oberkirchenrat, Bibliothek\n"
      + "1738\tSchmalkalden FH\tDE-Shm2\t\tDE-601\tHochschule  Schmalkalden, Cellarius Bibliothek\n"
      + "1739\tVechta UB\tDE-Va1\t\tDE-601\tUniversitätsbibliothek Vechta\n"
      + "1740\tWeimar UB\tDE-Wim2\t\tDE-601\tUB Weimar\n"
      + "1742\tChemnitz UB\tDE-Ch1\t\tDE-576\tTechnische Universität Chemnitz, Universitätsbibliothek\n"
      + "1745\tBremen La.ki.Bibl.\tDE-Bre4\t\tDE-601\tLandeskirchliche Bibliothek Bremen\n"
      + "1746\tGoettingen Otto-Hahn-Bibl.\tDE-Goe116\t\tDE-601\tOtto-Hahn-Bibliothek des Max-Planck-Instituts für biophysikalische Chemie\n"
      + "1748\tBerlin PTB\tDE-B108\t\tDE-601\tPhysikalisch-Technische Bundesanstalt, Institut Berlin, Bibliothek\n"
      + "1749\tOsnabrueck FH Teilb. Musik\tDE-959-2\t\tDE-601\tfrüher: Hochschule Osnabrück, Bibliothek, Teilbibliothek Musik\n"
      + "1750\tMarburg FSt Personalschriften FE\tDE-Mb108\t\tDE-Mb108\tForschungsstelle für Personalschriften an der Philipps-Universität Marburg\n"
      + "1751\tDresden ISGV SAEBI\tDE-D174a\t\tDE-D174a\tInstitut für Sächsische Geschichte und Volkskunde, Projekt \"Sächsische Biografie\"\n"
      + "1752\tMarburg Ev. HS Tabor\tDE-Mb109\t\tDE-Mb109\tEvangelische Hochschule Tabor, Bibliothek\n"
      + "1753\tBerlin UdK\tDE-B170\tSE\tDE-188\tUniversität der Künste Berlin, Universitätsbibliothek\n"
      + "1753\tBerlin UdK\tDE-B170\tFE\tDE-384\tUniversität der Künste Berlin, Universitätsbibliothek\n"
      + "1756\tGotha Schlossmuseum\tDE-G16\t\tDE-601\tStiftung Schloss Friedenstein Gotha, Bibliothek\n"
      + "1757\tKiel IFM-GEOMAR\tDE-Ki109\t\tDE-601\tHelmholtz-Zentrum für Ozeanforschung Kiel (GEOMAR), Bibliothek Westufer\n"
      + "1758\tBrandenburgische Technische Universität Cottbus - Senftenberg\tDE-634\t\tDE-521\tBrandenburgische Technische Universität Cottbus - Senftenberg, Universitätsbibliothek\n"
      + "1758\tCottbus BTU, SE\tDE-Co1\t\tDE-188\tCottbus BTU\n"
      + "1759\tEberswalde FH\tDE-Eb1\t\tDE-521\tHochschule für nachhaltige Entwicklung Eberswalde, Hochschulbibliothek\n"
      + "1762\tPotsdam TFA\tDE-Po84\t\tDE-101\tTheodor-Fontane-Archiv Universität Potsdam\n"
      + "1763\tHalle Franckesche Stiftungen\tDE-Ha33\t\tDE-601\tFranckesche Stiftungen, Studienzentrum August Hermann Francke, Archiv und Bibliothek\n"
      + "1764\tMarbach DLA\tDE-Mar1\t\tDE-576\tDeutsches Literaturarchiv Marbach, Bibliothek\n"
      + "1765\tMarburg DFG-Projekt Thenom\tDE-Mb111\t\tDE-Mb111\tDFG-Projekt Thenom (Thesaurus Nominum Auctorum et Mortuorum) an der Philipps-Universität Marburg, FB 06, Sozial- u. Wirtschaftsgeschichte\n"
      + "1766\tMarburg Foto\tDE-Mb112\t\tDE-Mb112\tDeutsches Dokumentationszentrum für Kunstgeschichte - Bildarchiv Foto Marburg\n"
      + "1767\tBad Koesen Landesschule Pforte\tDE-Pf1\t\tDE-Pf1\tLandesschule Pforte, Archiv und Bibliothek\n"
      + "1768\tHalle/S Marienbibliothek\tDE-Ha32\t\tDE-601\tMarienbibliothek\n"
      + "1769\tBern HLS Schweiz\tCH-001499-7\t\tCH-000001-5\tHistorisches Lexikon der Schweiz (HLS), Zentralredaktion\n"
      + "1770\tBern DoDIS\tCH-001661-0\t\tCH-000001-5\tBern DoDIS\n"
      + "1771\tBern Foto CH\tCH-001651-4\t\tCH-000001-5\tBern Foto CH\n"
      + "1772\tMuenchen BMLO\tDE-M512\t\tDE-12\tBayerisches Musiker-Lexikon Online\n"
      + "1773\tGoettingen Germ. Sacra\tDE-Goe172\t\tDE-601\tAkademie der Wissenschaften zu Göttingen, Germania Sacra\n"
      + "1774\tGoettingen Sanskrit Woerterbuch\tDE-7-911\t\tDE-601\tAkademie der Wissenschaften zu Göttingen, Sanskrit-Wörterbuch, Bibliothek\n"
      + "1775\tZuerich SIK\tCH-000479-X\t\tCH-000006-1\tZuerich SIK\n"
      + "1776\tLokalredaktion UB Basel, f \tCH-BaUGNF\t\tCH-BaUGNF\tBasel UB Portraitsammlung\n"
      + "XXXX\tLokalredaktion UB Basel, s\tCH-BaUGNS\t\tCH-BaUGNS\tBasel UB Portraitsammlung\n"
      + "XXXX\tLokalredaktion UB Basel Verbund\tCH-BaUGNV\t\tCH-BaUGNV\tBasel UB Portraitsammlung\n"
      + "XXXX\tLokalredaktion HAN\tCH-BaUGNH\t\tCH-BaUGNH\tBasel UB Portraitsammlung\n"
      + "1777\tBerlin Wikimedia Deutschland\tDE-B1592\t\tDE-B1592\tWikimedia Deutschland e.V., Bibliothek\n"
      + "1778\tBeirut Orient-Institut\tDE-Y9\t\tDE-601\tOrient-Institut Beirut\n"
      + "1779\tBremen Forschungsst. Osteuropa\tDE-Bre12\t\tDE-601\tForschungsstelle Osteuropa an der Universität Bremen - Bibliothek\n"
      + "1780\tWiesbaden Hess. Hauptstaatsarch.\tDE-Wi1\t\tDE-603\tHessisches Hauptstaatsarchiv, Bibliothek\n"
      + "1781\tMuencheberg Senckenberg DEI\tDE-B15\t\tDE-603\tSenckenberg Deutsches Entomologisches Institut, Entomologische Bibliothek\n"
      + "1782\tFrankfurt Staedel Museum\tDE-F10\t\tDE-603\tStädel Museum, Bibliothek\n"
      + "1783\tBad Homburg Stadtarchiv\tDE-Hog1\t\tDE-603\tStadtarchiv Bad Homburg vor der Höhe, Bibliothek\n"
      + "1784\tMainz NHM Naturhistor. Museum\tDE-Mz119\t\tDE-603\tNaturhistorisches Museum und Landessammlung für Naturkunde Mainz, Bibliothek\n"
      + "1785\tMittweida HS\tDE-Mit1\t\tDE-576\tHochschule Mittweida (FH), Hochschulbibliothek\n"
      + "1786\tZwickau HS\tDE-Zwi2\t\tDE-576\tWestsächsische Hochschule Zwickau, Bibliothek\n"
      + "1787\tDreseden LFA Sachsen\tDE-D115\t\tDE-576\tLandesamt für Archäologie Sachsen, Bibliothek\n"
      + "1788\tDresden HFM\tDE-D117\t\tDE-576\tHochschule für Musik 'Carl Maria von Weber', Hochschulbibliothek\n"
      + "1789\tDresden SKD\tDE-D13\t\tDE-576\tStaatliche Kunstsammlungen Dresden, Kunstbibliothek\n"
      + "1790\tFreiburg MFO\tDE-Frei3c\t\tDE-576\tMathematisches Forschungsinstitut Oberwolfach gGmbH, Bibliothek\n"
      + "1791\tFreiburg Caritas Bibl.\tDE-Frei26\t\tDE-576\tDeutscher Caritasverband e.V., Bibliothek\n"
      + "1792\tFreiburg MPI CC\tDE-Frei85\t\tDE-576\tMax-Planck-Institut für ausländisches und internationales Strafrecht, Bibliothek\n"
      + "1793\tFreiburg DVA\tDE-Frei99\t\tDE-576\tFreiburg DVA\n"
      + "1794\tFreiburg ABI\tDE-Frei119\t\tDE-576\tArnold-Bergstraesser-Institut für kulturwissenschaftliche Forschung, Bibliothek\n"
      + "1795\tFreiburg Augustiner-Museum\tDE-Frei123\t\tDE-576\tStädtische Museen Freiburg, Augustinermuseum/Museum für Neue Kunst, Bibliothek\n"
      + "1796\tKehl HS\tDE-Kh1\t\tDE-576\tHochschule für öffentliche Verwaltung Kehl, Bibliothek\n"
      + "1797\tOffenburg HS\tDE-Ofb1\t\tDE-576\tHochschule Offenburg, University of Applied Sciences, Bibliothek Campus Offenburg\n"
      + "1798\tHeidelberg PH\tDE-He76\t\tDE-576\tBibliothek der Pädagogischen Hochschule Heidelberg\n"
      + "1799\tHeidelberg MPIL\tDE-B208\t\tDE-576\tMax-Planck-Institut für ausländisches öffentliches Recht und Völkerrecht, Bibliothek\n"
      + "1801\tKarlsruhe BVerfG\tDE-Ka26\t\tDE-576\tBundesverfassungsgericht, Bibliothek\n"
      + "1802\tKarlsruhe HfM\tDE-Ka84\t\tDE-576\tHochschule für Musik Karlsruhe, Bibliothek\n"
      + "1803\tKarlsruhe ZKM\tDE-Ka88\t\tDE-576\tZentrum für Kunst und Medien Karlsruhe / Staatliche Hochschule für Gestaltung, Bibliothek\n"
      + "1804\tKarlsruhe Kunsthalle\tDE-Ka23\t\tDE-576\tStaatliche Kunsthalle, Bibliothek\n"
      + "1805\tLeipzig Bach-Archiv\tDE-L326\t\tDE-576\tBach-Archiv, Bibliothek\n"
      + "1806\tLeipzig BVerwG\tDE-B791\t\tDE-576\tBundesverwaltungsgericht, Bibliothek\n"
      + "1807\tLeipzig HTWK\tDE-L189\t\tDE-576\tHochschule für Technik, Wirtschaft und Kultur, Hochschulbibliothek\n"
      + "1808\tLeipzig HMT\tDE-L152\t\tDE-576\tHochschule für Musik und Theater 'Felix Mendelssohn Bartholdy', Hochschulbibliothek\n"
      + "1809\tMannheim MUHO\tDE-Mh31\t\tDE-576\tStaatliche Hochschule für Musik und Darstellende Kunst Mannheim, Bibliothek\n"
      + "1810\tMannheim TECHNOSEUM\tDE-Mh34\t\tDE-576\tTECHNOSEUM Landesmuseum für Technik und Arbeit, Bibliothek\n"
      + "1811\tStuttgart LKZB\tDE-Stg117\t\tDE-576\tLandeskirchliche Zentralbibliothek - Bibliothek des Evangelischen Oberkirchenrats\n"
      + "1812\tStuttgart Haus Birkach\tDE-Stg257\t\tDE-576\tEvangelisches Bildungszentrum Haus Birkach, Bibliothek\n"
      + "1813\tStuttgart HDG\tDE-Stg269\t\tDE-576\tHaus der Geschichte Baden-Württemberg, Bibliothek\n"
      + "1814\tStuttgart MH\tDE-Stg111\t\tDE-576\tStaatliche Hochschule für Musik und Darstellende Kunst Stuttgart, Bibliothek\n"
      + "1815\tStuttgart Stadtarchiv\tDE-Stg277\t\tDE-576\tStadtarchiv Stuttgart, Bibliothek\n"
      + "1816\tTrossingen MH\tDE-Trs1\t\tDE-576\tStaatliche Hochschule für Musik Trossingen, Hochschulbibliothek\n"
      + "1817\tStuttgart WABW\tDE-Stg256\t\tDE-576\tWirtschaftsarchiv Baden-Württemberg, Bibliothek\n"
      + "1818\tLudwigsburg DFI\tDE-Lg3\t\tDE-576\tDeutsch-Französisches Institut, Frankreich-Bibliothek\n"
      + "1819\tRottenburg DioezesanB\tDE-Rot2\t\tDE-576\tDiözesanbibliothek Rottenburg\n"
      + "1820\tSigmaringen STA\tDE-Sig1\t\tDE-576\tLandesarchiv Baden-Württemberg, Abteilung Staatsarchiv Sigmaringen, Bibliothek\n"
      + "1821\tTuebingen JS\tDE-21-24\t\tDE-576\tJuristisches Seminar, Bibliothek\n"
      + "1822\tMünchen Goethe-Zentr.\tDE-M504\t\tDE-576\tGoethe-Institut e. V. Zentrale, Bibliothek\n"
      + "1823\tHamburg MPI Priv.\tDE-B212\t\tDE-576\tMax-Planck-Institut für ausländisches und internationales Privatrecht, Bibliothek\n"
      + "1824\tKassel documenta Archiv\tDE-Ks17\t\tDE-576\tdocumenta archiv, Bibliothek\n"
      + "1825\tNuernberg GNM\tDE-N1\t\tDE-576\tGermanisches Nationalmuseum, Bibliothek\n"
      + "1826\tSpeyer DHV\tDE-Sp3\t\tDE-576\tDeutsche Universität für Verwaltungswissenschaften Speyer, Universitätsbibliothek\n"
      + "1827\tHannover Ev.Luth.Landesk.\tDE-Hv111\t\tDE-601\tEvangelisch-Lutherisches Landeskirchenamt, Bibliothek\n"
      + "1828\tBerlin GSTA\tDE-B41\tFE\tDE-601\tGeheimes Staatsarchiv Preußischer Kulturbesitz, Bibliothek\n"
      + "1828\tBerlin GSTA\tDE-B41\tSE\tDE-1\tGeheimes Staatsarchiv Preußischer Kulturbesitz, Bibliothek\n"
      + "1829\tBerlin SIM\tDE-B763\tFE\tDE-601\tStaatliches Institut für Musikforschung - Preußischer Kulturbesitz, Bibliothek\n"
      + "1829\tBerlin SIM\tDE-B763\tSE\tDE-1\tStaatliches Institut für Musikforschung - Preußischer Kulturbesitz, Bibliothek\n"
      + "1830\tBerlin KB\tDE-B11\tFE\tDE-601\tStaatliche Museen zu Berlin, Preußischer Kulturbesitz, Kunstbibliothek\n"
      + "1830\tBerlin KB\tDE-B11\tSE\tDE-1\tStaatliche Museen zu Berlin, Preußischer Kulturbesitz, Kunstbibliothek\n"
      + "1831\tDarmstadt HLM\tDE-Ds82\t\tDE-603\tHessisches Landesmuseum Darmstadt, Bibliothek\n"
      + "1832\tTübingen Brechtbau-Bib\tDE-21-108\t\tDE-576\tBrechtbau-Bibliothek\n"
      + "1833\tReutlingen HSB\tDE-Rt2\t\tDE-576\tHochschulbibliothek Reutlingen (Lernzentrum)\n"
      + "1834\tMannheim MZES\tDE-180-4-2\t\tDE-576\tMannheimer Zentrum für Europäische Sozialforschung, Bibliothek\n"
      + "1835\tGoerlitz OLB\tDE-Gl2\t\tDE-576\tOberlausitzische Bibliothek der Wissenschaften bei den Görlitzer Sammlungen\n"
      + "1836\tDresden HAIT\tDE-D264\t\tDE-576\tHannah-Arendt-Institut für Totalitarismusforschung e.V., Bibliothek\n"
      + "1837\tEsslingen Stadtarchiv\tDE-Ess4\t\tDE-576\tStadtarchiv Esslingen, Bibliothek\n"
      + "1838\tHamburg HS Musik\tDE-18-258\t\tDE-601\tHochschule für Musik und Theater, Bibliothek\n"
      + "1839\tHildesheim UB\tDE-Hil2\t\tDE-601\tUniversitätsbibliothek Hildesheim\n"
      + "1840\tErfurt TFM\tDE-Ef32\t\tDE-601\tThüringer Finanzministerium, Bibliothek\n"
      + "1841\tStuttgart Lindenmuseum\tDE-Stg5\t\tDE-576\tLinden-Museum Stuttgart, Bibliothek\n"
      + "1842\tZittau/Goerlitz HS\tDE-Zi4\t\tDE-576\tHochschule Zittau / Görlitz, Hochschulbibliothek\n"
      + "1843\tWeimar TLDA\tDE-Wim7\t\tDE-601\tLandesamt für Denkmalpflege und Archäologie, Dienststelle Weimar mit Museum für Ur- und Frühgeschichte Thüringens, Bibliothek\n"
      + "1844\tAurich LandschaftsB\tDE-Au3\t\tDE-601\tLandschaftsbibliothek Aurich\n"
      + "1845\tBerlin AdW B\tDE-B4\t\tDE-601\tBerlin-Brandenburgische Akademie der Wissenschaften, Akademiebibliothek\n"
      + "1846\tBerlin AdW GRA\tDE-B4-556\t\tDE-601\tBerlin, Berlin-Brandenburgische Akademie der Wissenschaften, Akademiebibliothek, Teilbibliothek Griechisch-römische Altertumskunde\n"
      + "1847\tMPI Bildungsforsch.\tDE-B1532\t\tDE-601\tMax-Planck-Institut für Bildungsforschung, Bibliothek und wissenschaftliche Information\n"
      + "1848\tCenter for World Music\tDE-Hil8\t\tDE-601\tCenter for World Music, Bibliothek\n"
      + "1849\tHamburger Kunsthalle\tDE-H13\t\tDE-601\tHamburger Kunsthalle, Bibliothek\n"
      + "1850\tHamburg Ärztl. Verein\tDE-H20\t\tDE-601\tÄrztekammer Hamburg, Bibliothek des Ärztlichen Vereins\n"
      + "1851\tMuseum Arbeit Hamburg\tDE-H353\t\tDE-601\tStiftung Historische Museen Hamburg, Museum der Arbeit, Bibliothek\n"
      + "1852\tMus. Hamburg. Geschichte\tDE-H77\t\tDE-601\tStiftung Historische Museen Hamburg, Museum für Hamburgische Geschichte, Bibliothek\n"
      + "1853\tRostock Inst.Ostseefor.\tDE-Wa1\t\tDE-601\tLeibniz-Institut für Ostseeforschung Warnemünde, Bibliothek\n"
      + "1854\tDummerstorf Inst Nutztierbiol.\tDE-R48\t\tDE-601\tLeibniz-Institut für Nutztierbiologie, Bibliothek\n"
      + "1855\tHamburg, Bibliothek Geowiss.\tDE-H144\t\tDE-601\tBehörde für Stadtentwicklung und Wohnen / Behörde für Umwelt und Energie - Bibliothek Stadtentwicklung, Umwelt und Geologie: Sondersammlung des Geologischen Landesamtes (GLA)\n"
      + "1856\tHamburg Mus. Völkerkunde\tDE-H16\t\tDE-601\tMuseum am Rothenbaum, Bibliothek\n"
      + "1857\tKassel MHK\tDE-Ks14\t\tDE-603\tMuseumslandschaft Hessen Kassel, Bibliothek\n"
      + "1858\tTuebingen IxTheo\tDE-Tue135\t\tDE-576\tIndex theologicus der Universitätsbibliothek Tübingen\n"
      + "1859\tMannheim IDS WGL\tDE-Mh39\t\tDE-576\tLeibniz-Institut für Deutsche Sprache (IDS), Bibliothek\n"
      + "1860\tStuttgart Landesmuseum\tDE-Stg266\t\tDE-576\tLandesmuseum Württemberg, Bibliothek\n"
      + "1861\tLoerrach Duale Hochschule BW\tDE-Loer2\t\tDE-576\tDuale Hochschule Baden-Württemberg Lörrach, Zentralbibliothek\n"
      + "1862\tBremerhaven A.-Wegener-Inst.\tDE-Bv2\t\tDE-601\tAlfred-Wegener-Institut Helmholtz-Zentrum für Polar- und Meeresforschung, (AWI), Bibliothek\n"
      + "1863\tHamburg Nordkirchenbibliothek\tDE-H99\t\tDE-601\tNordkirchenbibliothek im Bibliotheks- und Medienzentrum der Nordkirche\n"
      + "1864\tFreiburg HS Musik Bibl.\tDE-Frei50\t\tDE-576\tHochschule für Musik Freiburg, Bibliothek\n"
      + "1865\tSaarbruecken Stift. Kulturbesitz\tDE-Sa27\t\tDE-576\tStiftung Saarländischer Kulturbesitz, Bibliothek\n"
      + "1866\tBochum HSG\tDE-1866\t\tDE-576\tHochschule für Gesundheit, Hochschulbibliothek\n"
      + "1867\tWeimar Hauptstaatsarchiv\tDE-Wim6\t\tDE-601\tHauptstaatsarchiv Weimar, Bibliothek\n"
      + "1868\tZuerich, GTA\tCH-001803-8\t\tCH-000006-1\tZuerich, GTA\n"
      + "1869\tNuertingen HKT-Bibl.\tDE-1869\t\tDE-576\tHochschule für Wirtschaft und Umwelt Nürtingen-Geislingen, Bibliothek Campus Hauber\n"
      + "1870\tFrankfurt/M HFMDK\tDE-F78\t\tDE-603\tHochschule für Musik und Darstellende Kunst, Bibliothek\n"
      + "1871\tHamm ZfW\tDE-1871\t\tDE-576\tZentrum für Wissensmanagement, Bibliothek Hamm\n"
      + "1873\tFulda Priesterseminar\tDE-Ful2\t\tDE-603\tBibliothek des Bischöflichen Priesterseminars\n"
      + "1874\tLuebeck MusikHS\tDE-Lue12\t\tDE-601\tMusikhochschule Lübeck, Bibliothek\n"
      + "1875\tFFM Frau und Musik\tDE-Ks15\t\tDE-576\tArchiv Frau und Musik\n"
      + "1876\tFFM Stadtgeschichte\tDE-F186\t\tDE-576\tInstitut für Stadtgeschichte Frankfurt, Bibliothek\n"
      + "1877\tFFM FDH/FGM\tDE-F25\t\tDE-576\tFreies Deutsches Hochstift / Frankfurter Goethe-Museum, Bibliothek\n"
      + "1878\tFFM ARCHAEOL. MUS.\tDE-F225\t\tDE-576\tArchäologisches Museum Frankfurt, Bibliothek\n"
      + "1879\tFFM Kunsthandwerksmus.\tDE-F146\t\tDE-576\tMuseum für Angewandte Kunst, Bibliothek\n"
      + "1880\tFFM DIF\tDE-Wi17\t\tDE-576\tDFF - Deutsches Filminstitut & Filmmuseum, Bibliothek\n"
      + "1881\tFFM DAM\tDE-F219\t\tDE-576\tDeutsches Architekturmuseum, Bibliothek\n"
      + "1882\tOF Klingspor-Mus.\tDE-Of2\t\tDE-576\tKlingspor-Museum, Bibliothek und Archiv\n"
      + "1883\tFFM Hist. Mus.\tDE-F207\t\tDE-576\tHistorisches Museum, Bibliothek\n"
      + "1884\tFFM Rat f. Formgebung\tDE-Ds108\t\tDE-576\tRat für Formgebung - German Design Council, Bibliothek\n"
      + "1885\tSchweizer NB\tCH-001821-6\t\tCH-001821-6\tSchweizer NB\n"
      + "1923\tDNB\tDE-101\t\tDE-101\tDeutsche Nationalbibliothek\n"
      + "1926\tLippstadt ZfW\tDE-1926\t\tDE-576\tZentrum für Wissensmanagement, Bibliothek Lippstadt\n"
      + "1971\tFFM Weltkulturen Mus.\tDE-1971\t\tDE-576\tWeltkulturen Museum, Bibliothek\n"
      + "1973\tFFM STAEDELSCHULE\tDE-1973\t\tDE-576\tStaatliche Hochschule für Bildende Künste, Städelschule, Bibliothek\n"
      + "1975\tFFM MUS. MOD. KUNST\tDE-1975\t\tDE-576\tMuseum für Moderne Kunst, Bibliothek\n"
      + "1978\tFFM MUS. KOMMUNIKATION\tDE-1978\t\tDE-576\tMuseum für Kommunikation Frankfurt, Bibliothek\n"
      + "1979\tFFM JUED. MUS.\tDE-1979\t\tDE-576\tJüdisches Museum der Stadt Frankfurt am Main, Bibliothek\n"
      + "1995\tZDB\tDE-600\t\tDE-600\tZeitschriftendatenbank (ZDB)\n"
      + "1999\tBerlin BGK\tDE-109\t\tDE-609\tZentral- und Landesbibliothek Berlin, Haus Amerika-Gedenkbibliothek und Haus Berliner Stadtbibliothek sowie: Senatsbibliothek Berlin\n"
      + "2008\tBonn FIZ Bundeswehr\tDE-1073\t\tDE-605\tFachinformationszentrum der Bundeswehr (FIZBw) - Ausleihservice Hardthöhe\n"
      + "2100\tHG Kreisarchiv\tDE-1962\t\tDE-603\tKreisarchiv des Hochtaunuskreises\n"
      + "2101\tMPI Aesthetik\tDE-2177\t\tDE-603\tMax-Planck-Institut für empirische Ästhetik, Bibliothek\n"
      + "2102\tThurgau Kantonsbibl.\tCH-000086-2\t\tCH-000001-5\tKantonsbibliothek Thurgau\n"
      + "2103\tEisenbibliothek Schlatt\tCH-000728-7\t\tDE-576\tEisenbibliothek - Stiftung der Georg Fischer AG\n"
      + "2104\tNB, e-codices\tCH-001667-5\t\tCH-000001-5\tNB, e-codices\n"
      + "2105\tExLibris\tDE-632\t\tDE-632\tEx Libris (Deutschland) GmbH\n"
      + "2106\tBerlin Bundesrat\tDE-Bo151\t\tDE-576\tBundesrat, Bibliothek\n"
      + "2107\tGraz Steiermaerk. LB\tAT-LBST\t\tAT-NOELB\tSteiermärkische Landesbibliothek\n"
      + "2108\tOBVSG\tAT-OBVSG\t\tAT-OBV\tOBVSG\n"
      + "2109\tKarlsruhe Badisches Landesmus.\tDE-Ka23a\t\tDE-576\tBadisches Landesmuseum, Bibliothek\n"
      + "2110\tMannheim Stadtarchiv\tDE-Mh40\t\tDE-576\tMARCHIVUM\n"
      + "2111\tGotha Schlossmuseum\tDE-G16\tFE\tDE-576\tStiftung Schloss Friedenstein Gotha, Bibliothek\n"
      + "2112\tFrankfurt/M CIBEDO\tDE-2287\t\tDE-603\tChristlich-Islamische Begegnungs- und Dokumentationsstelle, Bibliothek\n"
      + "2113\tWeil/Rhein vdmb\tDE-Wlr1\t\tDE-576\tVitra Design Museum, Bibliothek\n"
      + "2114\tBerlin AA\tDE-B19\t\tDE-576\tAuswärtiges Amt, Referat 116, Bibliothek, Informationsvermittlung\n"
      + "2115\tFreiburg Staatsarchiv\tDE-Frei145\t\tDE-576\tLandesarchiv Baden-Württemberg, Abteilung Staatsarchiv Freiburg, Bibliothek\n"
      + "2116\tSalem KrsB\tDE-Sam1\t\tDE-576\tLandratsamt Bodenseekreis, Kulturamt, Kreisbibliothek\n"
      + "2117\tHamburg ZB Behoerden\tDE-H216\t\tDE-601\tZentrale Bibliothek Behörden Hamburger Straße\n"
      + "2118\tWernigerode Harzbuecherei\tDE-We21\t\tDE-601\tHarzbücherei Wernigerode\n"
      + "2119\tHalle/S Dt Akad Naturfor\tDE-Ha2\t\tDE-601\tDeutsche Akademie der Naturforscher Leopoldina, Bibliothek\n"
      + "2120\tBremen Seeverkehrswirtschaft\tDE-Bre2\t\tDE-601\tInstitut für Seeverkehrswirtschaft und Logistik, ISL InfoCenter/Bibliothek\n"
      + "2123\tBremen StB\tDE-478\t\tDE-601\tStadtbibliothek Bremen, Zentralbibliothek\n"
      + "2124\tBremen Ueberseemuseum\tDE-Bre3\t\tDE-601\tÜbersee-Museum, Bibliothek\n"
      + "2125\tKonstanz BSZ/MusIS\tDE-576-3\t\tDE-576-3\tBibliotheksservice-Zentrum Baden-Württemberg (BSZ) / MusIS\n"
      + "2130\tHamburg HfBK\tDE-18-26\t\tDE-601\tHochschule für Bildende Künste, Bibliothek\n"
      + "2133\tMainz Stadtarchiv Bibliothek\tDE-2397\t\tDE-603\tStadtarchiv Mainz, Bibliothek\n"
      + "2134\tKoethen HSB HSA\tDE-Kt1\t\tDE-601\tHochschule Anhalt , Hochschulbibliothek\n"
      + "2135\tBremen ZMT\tDE-Bre14\t\tDE-601\tLeibniz-Zentrum für Marine Tropenforschung (ZMT) GmbH, Bibliothek\n"
      + "2138\tHSC\tDE-2489\t\tDE-603\tHandschriftencensus (HSC) - Kompetenzzentrum Deutschsprachige Handschriften des Mittelalters\n"
      + "2139\tDuesseldorf ArchBiblEvKirche\tDE-Due72\t\tDE-576\tArchiv der Evangelischen Kirche im Rheinland, Bibliothek\n"
      + "2140\tLeipzig Museum Voelkerkunde\tDE-L228\t\tDE-576\tStaatliche Kunstsammlungen Dresden, Museum für Völkerkunde Leipzig, Bibliothek\n"
      + "2141\tBoppard Ev. Archivstelle\tDE-Bpd1\t\tDE-576\tEvangelische Archivstelle Boppard\n"
      + "2142\tBerlin DGAP\tDE-F131\t\tDE-576\tInformationszentrum der Deutschen Gesellschaft für Auswärtige Politik e.V.\n"
      + "2143\tBerlin SWP\tDE-B1567\t\tDE-576\tStiftung Wissenschaft und Politik (SWP), Bibliothek\n"
      + "2144\tBonn BICC\tDE-2421\t\tDE-576\tInternationales Konversionszentrum Bonn (BICC), Bibliothek\n"
      + "2145\tBonn DIE\tDE-B1503\t\tDE-576\tDeutsches Institut für Entwicklungspolitik, Bibliothek\n"
      + "2146\tFrankfurt HSFK\tDE-F197\t\tDE-576\tHessische Stiftung Friedens- und Konfliktforschung, Bibliothek\n"
      + "2147\tHamburg GIGA\tDE-H221\t\tDE-576\tGIGA German Institute of Global and Area Studies; Informationszentrum - Fachbibliotheken Afrika, Nahost und Lateinamerika\n"
      + "2148\tHamburg IFSH\tDE-18-226\t\tDE-576\tInstitut für Friedensforschung und Sicherheitspolitik an der Universität Hamburg, Bibliothek\n"
      + "2150\tStuttgart Landesarchiv A1u2\tDE-Stg285\t\tDE-576\tLandesarchiv Baden-Württemberg - Abteilungen 1 und 2, Bibliothek\n"
      + "2151\tStadtALB\tDE-Lg4\t\tDE-576\tStadtarchiv Ludwigsburg\n"
      + "2152\tDHI Rom\tDE-2491\t\tDE-576\tDeutsches Historisches Institut in Rom, Bibliothek\n"
      + "2153\tBautzen Sorbisches Inst.\tDE-Bn1\t\tDE-576\tSorbisches Institut e. V., Serbski institut z. t., Sorbische Zentralbibliothek, Serbska centralna biblioteka\n"
      + "2154\tHamburg Zeitgeschichte\tDE-H250\t\tDE-601\tForschungsstelle für Zeitgeschichte in Hamburg, Bibliothek\n"
      + "2155\tBad Oldesloe Kreisarchiv\tDE-2410\t\tDE-601\tKreisarchiv Stormarn\n"
      + "2164\tMainz Martinus-Bibl.\tDE-Mz2\t\tDE-603\tMartinus-Bibliothek, Wissenschaftliche Diözesanbibliothek\n"
      + "2165\tFrankfurt/M Fritz Bauer Inst.\tDE-2508\t\tDE-603\tBibliothek des Fritz Bauer Instituts zur Geschichte und Wirkung des Holocaust\n"
      + "2166\tRottweil Kreisarchiv\tDE-2156\t\tDE-576\tLandratsamt Rottweil, Stabsbereich Archiv, Kultur, Tourismus\n"
      + "2167\tKarlsruhe HSB\tDE-751\t\tDE-576\tHochschulbibliothek Karlsruhe (PH)\n"
      + "2168\tFreiburg PH\tDE-Frei129\t\tDE-576\tBibliothek der Pädagogischen Hochschule Freiburg/Breisgau\n"
      + "2170\tBerlin MPI Wiss.-Gesch.\tDE-B2226\t\tDE-601\tMax-Planck-Institut für Wissenschaftsgeschichte, Bibliothek\n"
      + "2171\tClausthal-Z. UB\tDE-104\tFE\tDE-601\tUniversitätsbibliothek Clausthal\n"
      + "2172\tStade Landsch.-Verb.\tDE-Sta5\t\tDE-601\tLandschaftsverband der ehemaligen Herzogtümer Bremen und Verden, Bibliothek\n"
      + "2173\tHalle/S IWH\tDE-2173\t\tDE-601\tLeibniz-Institut für Wirtschaftsforschung Halle, Bibliothek\n"
      + "2174\tBerlin VöBB\tDE-609\t\tDE-609\tVerbund der  Öffentlichen Bibliotheken Berlins - VÖBB\n"
      + "2175\tLeipzig IFL GZB\tDE-185\t\tDE-576\tLeibniz-Institut für Länderkunde, Geographische Zentralbibliothek\n"
      + "3032\tBerlin BBF/DIPF\tDE-B478\t\tDE-576\tBBF | Bibliothek für Bildungsgeschichtliche Forschung in Berlin\n"
      + "3032\tFrankfurt/M DIPF\tDE-F43\t\tDE-576\tDIPF | Leibniz-Institut für Bildungsforschung und Bildungsinformation, Bibliothek\n"
      + "3110\tLueneburg UB\tDE-Luen4\t\tDE-601\tLeuphana Universität Lüneburg, Medien- und Informationszentrum, Universitätsbibliothek\n"
      + "4025\tKoeln HBZ Elektron. Zsn\tDE-WWW2\t\tDE-605\tfrüher: Köln; Elektronische Zeitschriften Nordrhein-Westfalens und aus Teilen von Rheinland-Pfalz\n"
      + "4046\tHamburg Bamt Seeschifffahrt\tDE-H2\t\tDE-601\tBundesamt für Seeschifffahrt und Hydrographie, Bibliothek\n"
      + "4048\tWitzenhausen Arch Jugendbew\tDE-2355\t\tDE-603\tArchiv der deutschen Jugendbewegung\n"
      + "7777\tGBV\tDE-601\t\tDE-601\tVerbundzentrale des GBV (VZG)\n"
      + "41359\tUB Bern\tCH-BeUB\t\tCH-BeUB\tUniversitätsbibliothek Bern\n"
      + "8478\tLuzern ZHB\tCH-LnZHB\t\tCH-LnZHB\tZentral- und Hochschulbibliothek Luzern\n"
      + "41405\tUB St. Gallen\tCH-SgUB\t\tCH-SgUB\tUniversität St. Gallen, Bibliothek\n"
      + "41421\tLokalredaktion ZB Zürich, f\tCH-ZuZBF\t\tCH-ZuZBF\tZentralbibliothek Zürich, Formalerschliessung\n"
      + "41432\tLokalredaktion Uni Zürich, f\tCH-ZuUH\t\tCH-ZuUH\tUniversität Zürich, Hauptbibliothek\n"
      + "41411\tLokalredaktion ETH Zürich, f\tCH-ZuETHB\t\tCH-ZuETHB\tETH Zürich, ETH-Bibliothek, Redaktion Normdatei\n"
      + "41417\tLokalredaktion NEBIS VZ, f\tCH-ZuETHN\t\tCH-ZuETHN\tETH-Bibliothek, NEBIS-Verbundzentrale\n"
      + "41456\tZB Zürich, s\tCH-ZuZBS\t\tCH-ZuZBS\tZentralbibliothek Zürich, Sacherschliessung\n"
      + "9002\tBerlin SBB\tDE-1\tGKD\tDE-600\tStaatsbibliothek zu Berlin - Preußischer Kulturbesitz, Haus Unter den Linden\n"
      + "9003\tGKD-Redaktion DDB Frankfurt\tDE-101\tGKD\tDE-600\tDeutsche Nationalbibliothek\n"
      + "9004\tGKD-Redaktion BSB\tDE-12\tGKD\tDE-604\tBayerische Staatsbibliothek\n"
      + "9005\tÖBV\tAT-OBV\t\tAT-OBV\tÖsterreichischer Bibliothekenverbund\n"
      + "XXXX\tBVB\tDE-604\t\tDE-604\tBibliotheksverbund Bayern\n"
      + "XXXX\tKOBV\tDE-602\t\tDE-602\tKooperativer Bibliotheksverbund Berlin-Brandenburg\n"
      + "41679\tKantonsbibliothek Vadiana\tCH-SgKBLR\t\tCH-SgKBLR\tKantonsbibliothek Vadiana. GND Lokalredaktion\n"
      + "41680\tKantonsbibliothek Graubünden\tCH-ChKBLR\t\tCH-ChKBLR\tKantonsbibliothek Graubünden. GND-Lokalredaktion\n"
      + "35433\tAargauer Kantonsbibliothek\tCH-AaAKBLR\t\tCH-AaAKBLR\tAargauer Kantonsbibliothek. GND-Lokalredaktion\n"
      + "39245\tLiechtensteinische Landesbibliothek\tLI-VaLIL\t\tLI-VaLIL FLLB\tLiechtensteinische Landesbibliothek\n"
      + "" + "XXXX\tspio\tspio\t\tspio\tSpitzen, Exekutiv- und Informationsorgane\n"
      + "XXXX\tpseu\tpseu\t\tpseu\tAufspaltung von Pseudonymen\n";

  public static void main(final String... args) throws IOException {
    list2String();
  }

  /**
   * @throws IOException
   */
  public static void list2String() throws IOException {
    final Path path = Paths.get("src/de/dnb/gnd/utils/mx/liste.txt");
    final List<String> lines = Files.readAllLines(path);
    lines.forEach(line ->
    {
      line = line.replaceAll("\t", "\\\\" + "t");
      line = "\"" + line + "\\" + "n\" + ";
      System.out.println(line);
    });
  }

}
